/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a new user
         * @description Public endpoint. Rate limited by IP and email.
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{product_id}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List product reviews */
        get: operations["listProductReviews"];
        put?: never;
        /**
         * Create product review
         * @description Protected endpoint. User must have purchased the product. One review per user/product.
         */
        post: operations["createReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{product_id}/rating-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get product rating summary */
        get: operations["getRatingSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reviews/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete current user's review */
        delete: operations["deleteReview"];
        options?: never;
        head?: never;
        /** Update current user's review */
        patch: operations["updateReview"];
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lightweight health check */
        get: operations["healthLegacyRoot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lightweight health check */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/livez": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness check */
        get: operations["livez"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness check */
        get: operations["readyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Backward-compatible API health check */
        get: operations["apiHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Prometheus metrics
         * @description Public in local/dev. In production, expose only via internal network or reverse proxy allowlist.
         */
        get: operations["metrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user's cart */
        get: operations["getCart"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cart/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add product to cart */
        post: operations["addCartItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cart/items/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update cart item quantity */
        put: operations["updateCartItem"];
        post?: never;
        /** Remove cart item */
        delete: operations["deleteCartItem"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List current user's orders */
        get: operations["listMyOrders"];
        put?: never;
        /** Checkout current cart into an order */
        post: operations["checkout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one of the current user's orders */
        get: operations["getMyOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all orders
         * @description Admin only.
         */
        get: operations["listAdminOrders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get any order
         * @description Admin only.
         */
        get: operations["getAdminOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/orders/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update order status
         * @description Admin only. Allowed statuses are pending, paid, shipping, completed, cancelled.
         */
        patch: operations["updateOrderStatus"];
        trace?: never;
    };
    "/api/v1/admin/dashboard/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get admin dashboard stats
         * @description Admin only. Returns aggregate ecommerce metrics without exposing password hashes, tokens, or secrets.
         */
        get: operations["getAdminDashboardStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List admin audit activity logs
         * @description Admin only. Returns persisted audit logs for sensitive admin actions. Metadata is sanitized and does not include passwords, tokens, secrets, or raw Authorization headers.
         */
        get: operations["listAdminAuditLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wishlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List current user's wishlist */
        get: operations["listWishlist"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wishlist/products/{product_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add product to wishlist
         * @description Idempotent; adding the same product again returns success and does not duplicate rows.
         */
        post: operations["addWishlistProduct"];
        /**
         * Remove product from wishlist
         * @description Idempotent; removing a missing wishlist product still returns success.
         */
        delete: operations["removeWishlistProduct"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login and receive an access token
         * @description Public endpoint. Rate limited by IP and email.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout current token
         * @description Protected endpoint. Stores the token jti in the revocation store until token expiry.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current authenticated principal */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List categories */
        get: operations["listCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create category
         * @description Admin only.
         */
        post: operations["createCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List/search/filter products */
        get: operations["listProducts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get product detail */
        get: operations["getProduct"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create product
         * @description Admin only.
         */
        post: operations["createProduct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update product
         * @description Admin only.
         */
        put: operations["updateProduct"];
        post?: never;
        /**
         * Delete product
         * @description Admin only.
         */
        delete: operations["deleteProduct"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            /** @example false */
            success: boolean;
            /** @example validation failed */
            message: string;
        };
        PaginationMeta: {
            /** @example 1 */
            page: number;
            /** @example 20 */
            limit: number;
            /**
             * Format: int64
             * @example 42
             */
            total: number;
            /**
             * Format: int64
             * @description Backward-compatible pagination field.
             * @example 3
             */
            total_page: number;
            /**
             * Format: int64
             * @example 3
             */
            total_pages: number;
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            full_name: string;
            /** Format: password */
            password: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
        AuthUser: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            full_name: string;
            /** @enum {string} */
            role: "user" | "admin";
        };
        AuthData: {
            /**
             * @description JWT access token. Examples use placeholders only.
             * @example eyJhbGciOi...example
             */
            token: string;
            user: components["schemas"]["AuthUser"];
        };
        AuthResponseEnvelope: {
            /** @example true */
            success: boolean;
            /** @example login success */
            message: string;
            data: components["schemas"]["AuthData"];
        };
        MeData: {
            /** Format: uuid */
            user_id: string;
            /** @enum {string} */
            role: "user" | "admin";
        };
        MeResponseEnvelope: {
            success: boolean;
            /** @example authorized */
            message: string;
            data: components["schemas"]["MeData"];
        };
        NullableSuccessEnvelope: {
            /** @example true */
            success: boolean;
            /** @example ok */
            message: string;
            data?: unknown;
        };
        Category: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CreateCategoryRequest: {
            name: string;
            slug: string;
        };
        CategoryResponseEnvelope: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["Category"];
        };
        CategoryListResponseEnvelope: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["Category"][];
            meta?: components["schemas"]["PaginationMeta"];
        };
        Product: {
            /** Format: uuid */
            id: string;
            name: string;
            description: string;
            /**
             * Format: double
             * @example 300000
             */
            price: number;
            stock: number;
            /** Format: uuid */
            category_id: string;
            /** @example streetwear */
            style: string;
            /** @example black */
            color: string;
            /** Format: uri */
            image_url: string;
            /**
             * Format: double
             * @example 4.5
             */
            average_rating: number;
            /**
             * Format: int64
             * @example 2
             */
            review_count: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ProductMutationRequest: {
            name: string;
            description: string;
            /** @example 300000 */
            price: number;
            stock: number;
            /** Format: uuid */
            category_id: string;
            style: string;
            color: string;
            /** Format: uri */
            image_url: string;
        };
        ProductResponseEnvelope: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["Product"];
        };
        ProductListResponseEnvelope: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["Product"][];
            meta?: components["schemas"]["PaginationMeta"];
        };
        CartProduct: {
            /** Format: uuid */
            id?: string;
            name?: string;
            price?: number;
            stock?: number;
            /** Format: uri */
            image_url?: string;
            style?: string;
            color?: string;
        };
        CartItem: {
            /** Format: uuid */
            id?: string;
            product?: components["schemas"]["CartProduct"];
            quantity?: number;
            subtotal?: number;
        };
        Cart: {
            /** Format: uuid */
            cart_id?: string;
            /** Format: uuid */
            user_id?: string;
            items?: components["schemas"]["CartItem"][];
            total?: number;
        };
        AddCartItemRequest: {
            /** Format: uuid */
            product_id: string;
            quantity: number;
        };
        UpdateCartItemRequest: {
            quantity: number;
        };
        CartResponseEnvelope: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["Cart"];
        };
        OrderProduct: {
            /** Format: uuid */
            id?: string;
            name?: string;
            /** Format: uri */
            image_url?: string;
            style?: string;
            color?: string;
        };
        OrderItem: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            product_id?: string;
            quantity?: number;
            unit_price?: number;
            subtotal?: number;
            product?: components["schemas"]["OrderProduct"];
        };
        /** @description Minimal user info for admin order management. Does not include password hashes or tokens. */
        OrderUser: {
            /** Format: uuid */
            id?: string;
            /** Format: email */
            email?: string;
            full_name?: string;
            /** @enum {string} */
            role?: "user" | "admin";
        };
        Order: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            user_id?: string;
            user?: components["schemas"]["OrderUser"];
            /** @enum {string} */
            status?: "pending" | "paid" | "shipping" | "completed" | "cancelled";
            total_amount?: number;
            items?: components["schemas"]["OrderItem"][];
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        UpdateOrderStatusRequest: {
            /** @enum {string} */
            status: "pending" | "paid" | "shipping" | "completed" | "cancelled";
        };
        OrderResponseEnvelope: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["Order"];
        };
        OrderListResponseEnvelope: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["Order"][];
            meta?: components["schemas"]["PaginationMeta"];
        };
        OrdersByStatus: {
            /** Format: int64 */
            pending?: number;
            /** Format: int64 */
            paid?: number;
            /** Format: int64 */
            shipping?: number;
            /** Format: int64 */
            completed?: number;
            /** Format: int64 */
            cancelled?: number;
        };
        /** @description Minimal recent order row for admin dashboard. Does not include password hashes or tokens. */
        DashboardRecentOrder: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            user_id?: string;
            /** Format: email */
            user_email?: string;
            user_name?: string;
            /** @enum {string} */
            status?: "pending" | "paid" | "shipping" | "completed" | "cancelled";
            total_amount?: number;
            /** Format: date-time */
            created_at?: string;
        };
        DashboardLowStockProduct: {
            /** Format: uuid */
            id?: string;
            name?: string;
            stock?: number;
            price?: number;
            image_url?: string;
        };
        DashboardRevenueByDay: {
            /** @example 2026-06-06 */
            date?: string;
            revenue?: number;
        };
        DashboardTopProduct: {
            /** Format: uuid */
            id?: string;
            name?: string;
            image_url?: string;
            /** Format: int64 */
            quantity_sold?: number;
            revenue?: number;
        };
        AdminDashboardStats: {
            total_revenue?: number;
            /** Format: int64 */
            total_orders?: number;
            /** Format: int64 */
            total_products?: number;
            /** Format: int64 */
            total_users?: number;
            orders_by_status?: components["schemas"]["OrdersByStatus"];
            recent_orders?: components["schemas"]["DashboardRecentOrder"][];
            low_stock_products?: components["schemas"]["DashboardLowStockProduct"][];
            revenue_by_day?: components["schemas"]["DashboardRevenueByDay"][];
            top_products?: components["schemas"]["DashboardTopProduct"][];
        };
        AdminDashboardStatsResponseEnvelope: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["AdminDashboardStats"];
        };
        /** @description Persisted admin/security activity log. Sensitive fields such as passwords, raw tokens, secrets, and Authorization headers are never stored. */
        AuditLog: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            actor_user_id?: string;
            /** @enum {string} */
            actor_role?: "user" | "admin";
            /** @example admin.product.update */
            action?: string;
            /** @enum {string} */
            resource_type?: "product" | "category" | "order";
            resource_id?: string;
            /** @enum {string} */
            result?: "success" | "failed";
            /**
             * @example {
             *       "product_name": "Linen Overshirt",
             *       "stock": 8
             *     }
             */
            metadata?: {
                [key: string]: unknown;
            };
            ip?: string;
            user_agent?: string;
            request_id?: string;
            /** Format: date-time */
            created_at?: string;
        };
        AuditLogListResponseEnvelope: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["AuditLog"][];
            meta?: components["schemas"]["PaginationMeta"];
        };
        WishlistProduct: {
            /** Format: uuid */
            id?: string;
            name?: string;
            description?: string;
            price?: number;
            stock?: number;
            /** Format: uuid */
            category_id?: string;
            style?: string;
            color?: string;
            /** Format: uri */
            image_url?: string;
        };
        WishlistItem: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            user_id?: string;
            /** Format: uuid */
            product_id?: string;
            product?: components["schemas"]["WishlistProduct"];
            /** Format: date-time */
            created_at?: string;
        };
        WishlistResponseEnvelope: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["WishlistItem"][];
            meta?: components["schemas"]["PaginationMeta"];
        };
        Review: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            user_id?: string;
            /** Format: uuid */
            product_id?: string;
            /** Format: uuid */
            order_id?: string;
            rating?: number;
            comment?: string | null;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        CreateReviewRequest: {
            /** Format: uuid */
            order_id: string;
            rating: number;
            comment?: string | null;
        };
        UpdateReviewRequest: {
            rating: number;
            comment?: string | null;
        };
        ReviewResponseEnvelope: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["Review"];
        };
        ReviewListResponseEnvelope: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["Review"][];
            meta?: components["schemas"]["PaginationMeta"];
        };
        RatingSummary: {
            /**
             * Format: double
             * @example 4.5
             */
            average_rating?: number;
            /**
             * Format: int64
             * @example 12
             */
            review_count?: number;
            /**
             * @example {
             *       "1": 0,
             *       "2": 1,
             *       "3": 2,
             *       "4": 4,
             *       "5": 5
             *     }
             */
            rating_breakdown?: {
                [key: string]: number;
            };
        };
        RatingSummaryResponseEnvelope: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["RatingSummary"];
        };
        IDResponseEnvelope: {
            success?: boolean;
            message?: string;
            data?: {
                /** Format: uuid */
                id?: string;
            };
        };
        ProductIDResponseEnvelope: {
            success?: boolean;
            message?: string;
            data?: {
                /** Format: uuid */
                product_id?: string;
            };
        };
        HealthData: {
            /** @example up */
            status?: string;
            /** @example stylemind-backend */
            service?: string;
        };
        HealthResponseEnvelope: {
            /** @example true */
            success?: boolean;
            /** @example ok */
            message?: string;
            data?: components["schemas"]["HealthData"];
        };
        LivenessData: {
            /** @example up */
            status?: string;
        };
        LivenessResponseEnvelope: {
            /** @example true */
            success?: boolean;
            /** @example ok */
            message?: string;
            data?: components["schemas"]["LivenessData"];
        };
        DependencyStatus: {
            /** @enum {string} */
            status?: "up" | "down" | "skipped";
        };
        ReadinessData: {
            /** @enum {string} */
            status?: "ready" | "not_ready";
            dependencies?: {
                postgres?: components["schemas"]["DependencyStatus"];
                redis?: components["schemas"]["DependencyStatus"];
            };
        };
        ReadinessResponseEnvelope: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["ReadinessData"];
        };
    };
    responses: {
        /** @description Invalid payload, validation error, or invalid identifier/filter. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Missing, invalid, expired, or revoked Bearer token. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Authenticated user does not have permission for this resource/action. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Business conflict, such as duplicate product review. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Rate limit exceeded. */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Unexpected server error. Response does not expose internal SQL/stack details. */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Dependency unavailable or revocation store unavailable. */
        ServiceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Health check OK */
        HealthOK: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["HealthResponseEnvelope"];
            };
        };
    };
    parameters: {
        /** @example 1 */
        PageParam: number;
        /** @example 20 */
        LimitParam: number;
        ProductIDPath: string;
        ProductIDPathProductID: string;
        OrderIDPath: string;
        ReviewIDPath: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Register success */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    listProductReviews: {
        parameters: {
            query?: {
                /** @example 1 */
                page?: components["parameters"]["PageParam"];
                /** @example 20 */
                limit?: components["parameters"]["LimitParam"];
            };
            header?: never;
            path: {
                product_id: components["parameters"]["ProductIDPathProductID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Product reviews */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewListResponseEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: components["parameters"]["ProductIDPathProductID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReviewRequest"];
            };
        };
        responses: {
            /** @description Review created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewResponseEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getRatingSummary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: components["parameters"]["ProductIDPathProductID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rating summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RatingSummaryResponseEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    deleteReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ReviewIDPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Review deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IDResponseEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    updateReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ReviewIDPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateReviewRequest"];
            };
        };
        responses: {
            /** @description Review updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewResponseEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    healthLegacyRoot: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["HealthOK"];
        };
    };
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["HealthOK"];
        };
    };
    livez: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LivenessResponseEnvelope"];
                };
            };
        };
    };
    readyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ready */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponseEnvelope"];
                };
            };
            /** @description Not ready */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponseEnvelope"];
                };
            };
        };
    };
    apiHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["HealthOK"];
        };
    };
    metrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Prometheus text exposition format */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    getCart: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current cart */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartResponseEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    addCartItem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddCartItemRequest"];
            };
        };
        responses: {
            /** @description Cart updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartResponseEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    updateCartItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCartItemRequest"];
            };
        };
        responses: {
            /** @description Cart updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartResponseEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    deleteCartItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cart updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartResponseEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    listMyOrders: {
        parameters: {
            query?: {
                /** @example 1 */
                page?: components["parameters"]["PageParam"];
                /** @example 20 */
                limit?: components["parameters"]["LimitParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User orders */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderListResponseEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    checkout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Order created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponseEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getMyOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["OrderIDPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Order detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponseEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    listAdminOrders: {
        parameters: {
            query?: {
                /** @example 1 */
                page?: components["parameters"]["PageParam"];
                /** @example 20 */
                limit?: components["parameters"]["LimitParam"];
                /** @description Search by order id. */
                q?: string;
                status?: "pending" | "paid" | "shipping" | "completed" | "cancelled";
                user_id?: string;
                /** @description Created-at start date or RFC3339 timestamp. */
                from?: string;
                /** @description Created-at end date or RFC3339 timestamp. */
                to?: string;
                sort?: "newest" | "oldest";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All orders */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderListResponseEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getAdminOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["OrderIDPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Order detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponseEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    updateOrderStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["OrderIDPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOrderStatusRequest"];
            };
        };
        responses: {
            /** @description Order status updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponseEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getAdminDashboardStats: {
        parameters: {
            query?: {
                /** @description Order created-at start date or RFC3339 timestamp. */
                from?: string;
                /** @description Order created-at end date or RFC3339 timestamp. */
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dashboard stats */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminDashboardStatsResponseEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    listAdminAuditLogs: {
        parameters: {
            query?: {
                /** @example 1 */
                page?: components["parameters"]["PageParam"];
                /** @example 20 */
                limit?: components["parameters"]["LimitParam"];
                /** @example admin.order_status.update */
                action?: string;
                resource_type?: "product" | "category" | "order";
                actor_user_id?: string;
                result?: "success" | "failed";
                /** @description Created-at start date or RFC3339 timestamp. */
                from?: string;
                /** @description Created-at end date or RFC3339 timestamp. */
                to?: string;
                sort?: "newest" | "oldest";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audit logs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLogListResponseEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    listWishlist: {
        parameters: {
            query?: {
                /** @example 1 */
                page?: components["parameters"]["PageParam"];
                /** @example 20 */
                limit?: components["parameters"]["LimitParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Wishlist items */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WishlistResponseEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    addWishlistProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: components["parameters"]["ProductIDPathProductID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Wishlist product added */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductIDResponseEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    removeWishlistProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: components["parameters"]["ProductIDPathProductID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Wishlist product removed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductIDResponseEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Login success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logout success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NullableSuccessEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current principal */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponseEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    listCategories: {
        parameters: {
            query?: {
                /** @example 1 */
                page?: components["parameters"]["PageParam"];
                /** @example 20 */
                limit?: components["parameters"]["LimitParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Category list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryListResponseEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createCategory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCategoryRequest"];
            };
        };
        responses: {
            /** @description Category created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryResponseEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    listProducts: {
        parameters: {
            query?: {
                /**
                 * @description Keyword search across product name and description.
                 * @example hoodie
                 */
                q?: string;
                category_id?: string;
                /** @example 100000 */
                min_price?: number;
                /** @example 800000 */
                max_price?: number;
                /** @example streetwear */
                style?: string;
                /** @example black */
                color?: string;
                /** @example 4 */
                min_rating?: number;
                /** @example true */
                in_stock?: boolean;
                sort?: "newest" | "price_asc" | "price_desc" | "rating_desc" | "popular";
                /** @example 1 */
                page?: components["parameters"]["PageParam"];
                /** @example 20 */
                limit?: components["parameters"]["LimitParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Product list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductListResponseEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ProductIDPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Product detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductResponseEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createProduct: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductMutationRequest"];
            };
        };
        responses: {
            /** @description Product created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductResponseEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    updateProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ProductIDPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductMutationRequest"];
            };
        };
        responses: {
            /** @description Product updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductResponseEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    deleteProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ProductIDPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Product deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IDResponseEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
}
