package errs

import "errors"

var (
	ErrUnauthorized                 = errors.New("unauthorized")
	ErrInvalidPayload               = errors.New("invalid payload")
	ErrInvalidID                    = errors.New("invalid id")
	ErrInvalidSort                  = errors.New("invalid sort")
	ErrValidationFailed             = errors.New("validation failed")
	ErrInvalidCredentials           = errors.New("invalid credentials")
	ErrEmailAlreadyExists           = errors.New("email already exists")
	ErrUserNotFound                 = errors.New("user not found")
	ErrInvalidUserRole              = errors.New("invalid user role")
	ErrInvalidUserStatus            = errors.New("invalid user status")
	ErrCannotDemoteLastAdmin        = errors.New("cannot demote the last admin")
	ErrCannotDisableSelf            = errors.New("cannot disable yourself")
	ErrCannotDisableLastAdmin       = errors.New("cannot disable the last admin")
	ErrUserDisabled                 = errors.New("user disabled")
	ErrProductNotFound              = errors.New("product not found")
	ErrCategoryNotFound             = errors.New("category not found")
	ErrCartEmpty                    = errors.New("cart is empty")
	ErrCartItemNotFound             = errors.New("cart item not found")
	ErrInvalidQuantity              = errors.New("quantity must be greater than 0")
	ErrInsufficientStock            = errors.New("insufficient stock")
	ErrOrderNotFound                = errors.New("order not found")
	ErrInvalidOrderStatus           = errors.New("invalid order status")
	ErrInvalidOrderStatusTransition = errors.New("invalid order status transition")
	ErrReviewNotFound               = errors.New("review not found")
	ErrReviewAlreadyExists          = errors.New("review already exists")
	ErrProductNotPurchased          = errors.New("product not purchased")
	ErrForbidden                    = errors.New("forbidden")
)
